Role.find_or_create_by name: 'Programmer'
Role.find_or_create_by name: 'Designer'
Role.find_or_create_by name: 'DBA'
Role.find_or_create_by name: 'Tester'
Role.find_or_create_by name: 'Product Owner'
Role.find_or_create_by name: 'SCRUM Master'